# Nixpacks configuration for Railway
[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm-8"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start"

[variables]
NODE_ENV = "production"